let students = [
    {
        name: "Pablo",
        surname: "Diaz",
        age: 22,
        city: "Villamayor",
        hobby: "Ski",
        favoriteFood: "SmashBurger",
        favoriteVideogame: "Escape From Tarkov",
        favoriteFilm: "Eyes Wide Shut",
        favoriteBook: "El Visitante",
        petName: "Tango",
    },
    {
        name:"Miguel",
        surname:"Abato",
        age:30,
        city:"Sevilla",
        hobby:"Gimnasio",
        favoriteFood:"Pasta",
        favoriteVideoGame:"FIFA",
        favoriteFilm:"Señor de los anillos",
        favoriteBook:"Imperio final",
        petName: "Lupo",
    }];