let students = [{
    name: "Pablo",
    surname: "Diaz",
    age: "22",
    city: "Villamayor",
    hobby: "Ski",
    favoriteFood: "SmashBurger",
    favoriteVideogame: "Escape From Tarkov",
    favoriteFilm: "Eyes Wide Shut",
    favoriteBook: "El Visitante",
    petName: "Tango",
},
{
    name: "Daniel",
    surname: "Segalés",
    age: 30,
    city: "Barbera",
    hobby: "Pottery",
    favoriteFood: "Fried Egg",
    favoriteVideogame: "Genshin Impact",
    favoriteFilm: "Nightmare Before Christmas",
    favoriteBook: "Sisifu's Myth",
    petName: "Dolent",
},
{
    name:"Miguel",
    surname:"Abato",
    age:30,
    city:"Sevilla",
    hobby:"Gimnasio",
    favoriteFood:"Pasta",
    favoriteVideoGame:"FIFA",
    favoriteFilm:"Señor de los anillos",
    favoriteBook:"Imperio final",
    petName: "Lupo",
},
{
    name:"Marilyn",
    surname:"Duran",
    age: 28,
    city:"Cadiz",
    hobby:"Gimnasio",
    favoriteFood:"Pasta",
    favoriteVideoGame:"N/A",
    favoriteFilm:"Outlander",
    favoriteBook:"Ikigai",
    petName: "N/A",
}];